#!/bin/sh

commit_msg_file="$1"
commit_msg=$(sed -n '1p' "$commit_msg_file")

hook_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
validator_script="$hook_dir/../scripts/validate-commit-msg.sh"

"$validator_script" "$commit_msg"
