#!/usr/bin/env bash

# Non-interactive environment and connectivity validation for Atlassy QA.
# Canonical usage: make qa-check
#
# Exit 0 = all required checks pass.
# Exit 1 = one or more required checks failed.
#
# Requires qa/.env.local generated by make qa-setup.

set -euo pipefail

# --- Resolve paths ------------------------------------------------------------

_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
_qa_dir="$(cd "${_script_dir}/.." && pwd)"
_env_file="${_qa_dir}/.env.local"

# --- Output helpers -----------------------------------------------------------

_pass_count=0
_warn_count=0
_fail_count=0

pass() {
  printf '[PASS] %s\n' "$1"
  _pass_count=$((_pass_count + 1))
}

warn() {
  printf '[WARN] %s\n' "$1"
  _warn_count=$((_warn_count + 1))
}

fail() {
  printf '[FAIL] %s\n' "$1" >&2
  _fail_count=$((_fail_count + 1))
}

fatal() {
  fail "$1"
  printf '\nEnvironment check failed. Fix the issue above and re-run.\n' >&2
  exit 1
}

# --- Check 1: curl availability -----------------------------------------------

if command -v curl >/dev/null 2>&1; then
  pass "curl is available ($(command -v curl))"
else
  fatal "curl is not installed. Install curl and re-run."
fi

# --- Check 2: Load qa/.env.local ----------------------------------------------

if [ ! -f "${_env_file}" ]; then
  fatal "qa/.env.local not found. Run 'make qa-setup' first."
fi

if [ ! -r "${_env_file}" ]; then
  fatal "qa/.env.local is not readable. Fix file permissions and re-run."
fi

set -a
# shellcheck disable=SC1090
. "${_env_file}"
set +a
pass "Loaded values from ${_env_file}"

# --- Check 3: ATLASSY_CONFLUENCE_BASE_URL set ---------------------------------

if [ -z "${ATLASSY_CONFLUENCE_BASE_URL:-}" ]; then
  fatal "ATLASSY_CONFLUENCE_BASE_URL is not set."
else
  pass "ATLASSY_CONFLUENCE_BASE_URL is set (${ATLASSY_CONFLUENCE_BASE_URL})"
fi

# --- Check 4: URL starts with https:// ----------------------------------------

case "${ATLASSY_CONFLUENCE_BASE_URL}" in
  https://*)
    pass "Base URL uses https://"
    ;;
  http://*)
    fatal "Base URL uses http:// instead of https://. Confluence Cloud requires https."
    ;;
  *)
    fatal "Base URL does not start with https:// (got: ${ATLASSY_CONFLUENCE_BASE_URL})."
    ;;
esac

# --- Check 5: URL does not end with /wiki -------------------------------------

case "${ATLASSY_CONFLUENCE_BASE_URL}" in
  */wiki)
    warn "Base URL ends with /wiki. The runtime appends /wiki automatically. Consider removing it."
    ;;
  *)
    pass "Base URL does not have trailing /wiki"
    ;;
esac

# --- Check 6: ATLASSY_CONFLUENCE_EMAIL set ------------------------------------

if [ -z "${ATLASSY_CONFLUENCE_EMAIL:-}" ]; then
  fatal "ATLASSY_CONFLUENCE_EMAIL is not set."
else
  pass "ATLASSY_CONFLUENCE_EMAIL is set"
fi

# --- Check 7: ATLASSY_CONFLUENCE_API_TOKEN set --------------------------------

if [ -z "${ATLASSY_CONFLUENCE_API_TOKEN:-}" ]; then
  fatal "ATLASSY_CONFLUENCE_API_TOKEN is not set."
else
  pass "ATLASSY_CONFLUENCE_API_TOKEN is set (length: ${#ATLASSY_CONFLUENCE_API_TOKEN})"
fi

# --- Check 8: Token length sanity ---------------------------------------------

if [ "${#ATLASSY_CONFLUENCE_API_TOKEN}" -lt 8 ]; then
  warn "API token is shorter than 8 characters. This looks suspicious."
else
  pass "API token length is reasonable (${#ATLASSY_CONFLUENCE_API_TOKEN} chars)"
fi

# --- Check 9: Confluence API connectivity -------------------------------------

_api_url="${ATLASSY_CONFLUENCE_BASE_URL}/wiki/rest/api/user/current"
printf '\nProbing Confluence API at %s ...\n' "${_api_url}"

_http_code=$(curl -s -o /dev/null -w "%{http_code}" \
  --max-time 10 \
  -u "${ATLASSY_CONFLUENCE_EMAIL}:${ATLASSY_CONFLUENCE_API_TOKEN}" \
  "${_api_url}" 2>/dev/null || echo "000")

case "${_http_code}" in
  200)
    pass "Confluence API connectivity (HTTP ${_http_code})"
    ;;
  401)
    fatal "Confluence API returned HTTP 401 (Unauthorized). Check email and API token."
    ;;
  403)
    fatal "Confluence API returned HTTP 403 (Forbidden). Check API token permissions."
    ;;
  404)
    fatal "Confluence API returned HTTP 404. Check ATLASSY_CONFLUENCE_BASE_URL is correct."
    ;;
  000)
    fatal "Confluence API unreachable (connection failed or timed out). Check URL and network."
    ;;
  *)
    fatal "Confluence API returned unexpected HTTP ${_http_code}."
    ;;
esac

# --- Check 10: Optional variables summary -------------------------------------

printf '\nOptional variables:\n'
if [ -n "${PAGE_ID:-}" ]; then
  printf '  PAGE_ID=%s\n' "${PAGE_ID}"
else
  printf '  PAGE_ID=(not set)\n'
fi
if [ -n "${SPACE_KEY:-}" ]; then
  printf '  SPACE_KEY=%s\n' "${SPACE_KEY}"
else
  printf '  SPACE_KEY=(not set)\n'
fi
if [ -n "${ARTIFACTS_DIR:-}" ]; then
  printf '  ARTIFACTS_DIR=%s\n' "${ARTIFACTS_DIR}"
else
  printf '  ARTIFACTS_DIR=(not set, defaults to .)\n'
fi

# --- Summary ------------------------------------------------------------------

printf '\n---\n'
printf 'Results: %d passed, %d warnings, %d failed\n' "${_pass_count}" "${_warn_count}" "${_fail_count}"

if [ "${_fail_count}" -gt 0 ]; then
  printf 'Environment check FAILED.\n' >&2
  exit 1
fi

printf 'All checks passed. Environment is ready for QA execution.\n'
exit 0
