#!/usr/bin/env bash

# Interactive setup for Atlassy QA environment variables.
# Canonical usage: make qa-setup

set -euo pipefail

_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
_qa_dir="$(cd "${_script_dir}/.." && pwd)"
_env_file="${_qa_dir}/.env.local"

# Load existing values as prompt defaults when available.
if [ -f "${_env_file}" ]; then
  # shellcheck disable=SC1090
  . "${_env_file}"
fi

atlassy_prompt() {
  _var_name="$1"
  _label="$2"
  _default="$3"

  if [ -n "${_default}" ]; then
    printf '%s [%s]: ' "${_label}" "${_default}"
  else
    printf '%s: ' "${_label}"
  fi

  _input=''
  IFS= read -r _input || true
  if [ -z "${_input}" ]; then
    _input="${_default}"
  fi

  printf -v "${_var_name}" '%s' "${_input}"
}

atlassy_prompt_secret() {
  _var_name="$1"
  _label="$2"
  _default="$3"

  if [ -n "${_default}" ]; then
    printf '%s [hidden, Enter keeps current]: ' "${_label}"
  else
    printf '%s: ' "${_label}"
  fi

  _input=''
  IFS= read -r -s _input || true
  printf '\n'

  if [ -z "${_input}" ]; then
    _input="${_default}"
  fi

  printf -v "${_var_name}" '%s' "${_input}"
}

atlassy_prompt \
  ATLASSY_CONFLUENCE_BASE_URL \
  'ATLASSY_CONFLUENCE_BASE_URL (example: https://yourdomain.atlassian.net)' \
  "${ATLASSY_CONFLUENCE_BASE_URL:-}"

ATLASSY_CONFLUENCE_BASE_URL="${ATLASSY_CONFLUENCE_BASE_URL%/}"
case "${ATLASSY_CONFLUENCE_BASE_URL}" in
  */wiki)
    ATLASSY_CONFLUENCE_BASE_URL="${ATLASSY_CONFLUENCE_BASE_URL%/wiki}"
    printf 'Adjusted base URL by removing trailing /wiki.\n'
    ;;
esac

atlassy_prompt \
  ATLASSY_CONFLUENCE_EMAIL \
  'ATLASSY_CONFLUENCE_EMAIL' \
  "${ATLASSY_CONFLUENCE_EMAIL:-}"

atlassy_prompt_secret \
  ATLASSY_CONFLUENCE_API_TOKEN \
  'ATLASSY_CONFLUENCE_API_TOKEN' \
  "${ATLASSY_CONFLUENCE_API_TOKEN:-}"

atlassy_prompt PAGE_ID 'PAGE_ID (optional)' "${PAGE_ID:-}"
atlassy_prompt SPACE_KEY 'SPACE_KEY (optional, for create-subpage)' "${SPACE_KEY:-}"
atlassy_prompt ARTIFACTS_DIR 'ARTIFACTS_DIR' "${ARTIFACTS_DIR:-.}"

_atlassy_fail=0

if [ -z "${ATLASSY_CONFLUENCE_BASE_URL}" ]; then
  printf 'ATLASSY_CONFLUENCE_BASE_URL is required.\n' >&2
  _atlassy_fail=1
fi

if [ -z "${ATLASSY_CONFLUENCE_EMAIL}" ]; then
  printf 'ATLASSY_CONFLUENCE_EMAIL is required.\n' >&2
  _atlassy_fail=1
fi

if [ -z "${ATLASSY_CONFLUENCE_API_TOKEN}" ]; then
  printf 'ATLASSY_CONFLUENCE_API_TOKEN is required.\n' >&2
  _atlassy_fail=1
fi

if [ "${_atlassy_fail}" -eq 1 ]; then
  unset -f atlassy_prompt atlassy_prompt_secret
  unset _script_dir _qa_dir _env_file _atlassy_fail
  exit 1
fi

if [ -z "${ARTIFACTS_DIR}" ]; then
  ARTIFACTS_DIR='.'
fi

{
  printf '# Generated by qa/scripts/setup-confluence-env.sh\n'
  printf '# Do not commit this file. It is git-ignored.\n'
  printf 'ATLASSY_CONFLUENCE_BASE_URL="%s"\n' "${ATLASSY_CONFLUENCE_BASE_URL}"
  printf 'ATLASSY_CONFLUENCE_EMAIL="%s"\n' "${ATLASSY_CONFLUENCE_EMAIL}"
  printf 'ATLASSY_CONFLUENCE_API_TOKEN="%s"\n' "${ATLASSY_CONFLUENCE_API_TOKEN}"
  printf 'ARTIFACTS_DIR="%s"\n' "${ARTIFACTS_DIR}"
  if [ -n "${PAGE_ID}" ]; then
    printf 'PAGE_ID="%s"\n' "${PAGE_ID}"
  fi
  if [ -n "${SPACE_KEY}" ]; then
    printf 'SPACE_KEY="%s"\n' "${SPACE_KEY}"
  fi
} > "${_env_file}"

chmod 600 "${_env_file}"
printf '\nWritten to %s (chmod 600).\n' "${_env_file}"

printf '\nConfigured environment variables:\n'
printf '  ATLASSY_CONFLUENCE_BASE_URL=%s\n' "${ATLASSY_CONFLUENCE_BASE_URL}"
printf '  ATLASSY_CONFLUENCE_EMAIL=%s\n' "${ATLASSY_CONFLUENCE_EMAIL}"
printf '  ATLASSY_CONFLUENCE_API_TOKEN=<hidden, length %s>\n' "${#ATLASSY_CONFLUENCE_API_TOKEN}"
printf '  ARTIFACTS_DIR=%s\n' "${ARTIFACTS_DIR}"
if [ -n "${PAGE_ID}" ]; then
  printf '  PAGE_ID=%s\n' "${PAGE_ID}"
fi
if [ -n "${SPACE_KEY}" ]; then
  printf '  SPACE_KEY=%s\n' "${SPACE_KEY}"
fi

printf '\nReady. Next step:\n'
printf '  make qa-check\n'

printf '\nExample preflight command:\n'
printf '  cargo run -p atlassy-cli -- run --request-id live-preflight-001 --page-id "${PAGE_ID:-REPLACE_PAGE_ID}" --edit-intent "sandbox preflight" --mode no-op --runtime-backend live --force-verify-fail --artifacts-dir "${ARTIFACTS_DIR}"\n'

unset -f atlassy_prompt atlassy_prompt_secret
unset _script_dir _qa_dir _env_file _atlassy_fail
